# Suites numériques — expérimentations

Compagnon pratique du chapitre *Suites Numériques* du carnet de recherche : implémentation et vérification numérique des notions vues en cours (génération de suites, majoration/minoration/bornitude, monotonie).

## 1. Génération de suites

Trois façons de produire les termes d'une suite : terme général $u_n = f(n)$, relation de récurrence $u_{n+1} = f(u_n)$, et le cas classique de Fibonacci.

In [2]:
def terme_general(f , debut , fin):
    """ renvoie la liste pour u_n = f(n) """

    return [f(n) for n in range(debut, fin + 1)]

# jeux de tests

u = lambda n : (-1) ** n / n
print(terme_general(u,1,5))

[-1.0, 0.5, -0.3333333333333333, 0.25, -0.2]


In [3]:
def suite_recurrente(f,u0,N):
    """ renvoie [u0, u1, ..., uN] pour la recurrence """

    termes = [u0]
    u = u0
    for _ in range (N):
        u = f(u)
        termes.append(u)
    return termes


# jeux de tests
from math import sqrt
f = lambda x : 1 + sqrt(x)
print(suite_recurrente(f,2,6))

[2, 2.414213562373095, 2.5537739740300376, 2.5980531824786173, 2.6118477541252516, 2.616121206508117, 2.6174427985273905]


In [4]:
def fibonacci(N):
    """ renvoie les N+1 premiers termes de la suite de Fibonacci (u0 = u1 = 1) """

    termes = [1,1]
    for _ in range(N - 1):
        termes.append(termes[-1] + termes[-2])
    return termes

print(fibonacci(10))

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


## 2. Propriétés d'une suite : majoration, minoration, bornitude, monotonie

Chaque fonction prend en entrée une liste de termes déjà calculée (via `terme_general` ou `suite_recurrente`) et teste la propriété correspondante — même logique que les exercices 1.1-1.3 du carnet.

In [5]:
def est_majoree(termes):
    """ teste sur les termes fournis """

    return max(termes)

In [6]:
def est_minoree(termes):
    """ teste sur les termes fournis """

    return min(termes)

In [7]:
def est_bornee(termes):
    """ majoree et bornee """

    return max(abs(u) for u in termes)

In [8]:
def est_croissante(termes):
    return all(termes[n+1] >= termes[n] for n in range(len(termes) -1))
               

In [9]:
def est_decroissante(termes):
    return all(termes[n+1] <= termes[n] for n in range(len(termes) - 1))

In [10]:
def est_monotone(termes):
    """ croissante ou decroissante """
    return est_croissante(termes) or est_decroissante(termes)
    

## 3. Vérification sur un exemple

Application des fonctions ci-dessus à $u_n = \dfrac{(-1)^n}{n}$ pour $n \in \{1, \dots, 99\}$.

In [11]:
u = lambda n : (-1)**n / n
termes = [u(n) for n in range(1,100)]

print("majorée par :", est_majoree(termes))     # ~0.5
print("minorée par :", est_minoree(termes))     # -1.0
print("bornée, |u_n| ≤ :", est_bornee(termes))  # 1.0
print("croissante ?", est_croissante(termes))   # False
print("décroissante ?", est_decroissante(termes)) # False
print("monotone ?", est_monotone(termes))       # False

majorée par : 0.5
minorée par : -1.0
bornée, |u_n| ≤ : 1.0
croissante ? False
décroissante ? False
monotone ? False


---

## 4. Espaces vectoriels ℝⁿ — vérifications numériques

Section à part, sans lien avec les suites : amorce du chapitre suivant. Génération de vecteurs/scalaires aléatoires, puis vérification numérique des axiomes de structure d'espace vectoriel et du critère de sous-espace vectoriel.

In [12]:
import numpy as np



In [13]:
rng = np.random.default_rng(42)
n = 4

def vecteur():
    return rng.integers(-9,10, size = n).astype(float)

def scalaire():
    return float(rng.integers(-9,10))

u , v , w = vecteur(), vecteur(),vecteur()
lam , mu = scalaire() , scalaire()

print("u =", u)
print("v =", v)
print("w =", w)
print("λ =", lam, "  µ =", mu)


                 

u = [-8.  5.  3. -1.]
v = [-1.  7. -8.  4.]
w = [-6. -8.  1.  9.]
λ = 4.0   µ = 5.0


### 4.1 Axiomes de structure d'espace vectoriel — addition

Commutativité, associativité, élément neutre, symétrique (opposé).

In [14]:
zero = np.zeros(n)

# 1. Commutativité
print("1. Commutativité   u+v = v+u        :", np.allclose(u + v, v + u))

# 2. Associativité
print("2. Associativité   u+(v+w)=(u+v)+w  :", np.allclose(u + (v + w), (u + v) + w))

# 3. Élément neutre
print("3. Neutre          u + 0 = u        :", np.allclose(u + zero, u))

# 4. Symétrique (opposé)
print("4. Symétrique      u + (-u) = 0     :", np.allclose(u + (-u), zero))



1. Commutativité   u+v = v+u        : True
2. Associativité   u+(v+w)=(u+v)+w  : True
3. Neutre          u + 0 = u        : True
4. Symétrique      u + (-u) = 0     : True


### 4.2 Axiomes de structure d'espace vectoriel — multiplication scalaire

$1 \cdot u = u$, associativité mixte $\lambda(\mu u) = (\lambda\mu)u$, distributivité sur les vecteurs et sur les scalaires.

In [15]:
# 5. 1 · u = u
print("5. 1·u = u                          :", np.allclose(1 * u, u))

# 6. λ·(µ·u) = (λµ)·u
print("6. λ·(µ·u) = (λµ)·u                 :", np.allclose(lam * (mu * u), (lam * mu) * u))

# 7. Distributivité / addition des vecteurs : λ·(u+v) = λu + λv
print("7. λ·(u+v) = λu + λv                :", np.allclose(lam * (u + v), lam * u + lam * v))

# 8. Distributivité / addition des scalaires : (λ+µ)·u = λu + µu
print("8. (λ+µ)·u = λu + µu                :", np.allclose((lam + mu) * u, lam * u + mu * u))

5. 1·u = u                          : True
6. λ·(µ·u) = (λµ)·u                 : True
7. λ·(u+v) = λu + λv                : True
8. (λ+µ)·u = λu + µu                : True


### 4.3 Propriétés élémentaires déduites des axiomes

$0 \cdot u = 0_E$, $\lambda \cdot 0_E = 0_E$, $(-1) \cdot u = -u$.

In [16]:
# Rappel : zero = np.zeros(n) est le vecteur nul 0_E
zero = np.zeros(n)

# 1. 0 · u = 0_E   (le scalaire 0 annule tout vecteur)
print("1. 0·u = 0_E              :", np.allclose(0 * u, zero))

# 2. λ · 0_E = 0_E  (multiplier le vecteur nul donne le vecteur nul)
print("2. λ·0_E = 0_E            :", np.allclose(lam * zero, zero))

# 3. (-1) · u = -u  (le scalaire -1 donne l'opposé)
print("3. (-1)·u = -u           :", np.allclose((-1) * u, -u))

1. 0·u = 0_E              : True
2. λ·0_E = 0_E            : True
3. (-1)·u = -u           : True


### 4.4 Intégrité : $\lambda \cdot u = 0_E \implies \lambda = 0$ ou $u = 0_E$

Un scalaire non nul et un vecteur non nul ne peuvent jamais donner le vecteur nul par multiplication scalaire.

In [17]:
# Sens intéressant : si λ·u = 0_E, alors forcément λ=0 OU u=0_E.
# Autrement dit : un scalaire non nul et un vecteur non nul ne peuvent
# JAMAIS donner le vecteur nul.

# Test : λ non nul, u non nul  ->  λ·u ne doit PAS être nul
lam_nonnul = 3.0
u_nonnul = vecteur()
produit = lam_nonnul * u_nonnul

print("λ =", lam_nonnul, " non nul")
print("u =", u_nonnul, " non nul")
print("λ·u =", produit)
print("λ·u est-il nul ?", np.allclose(produit, zero))   # attendu : False

λ = 3.0  non nul
u = [ 4.  5.  0. -7.]  non nul
λ·u = [ 12.  15.   0. -21.]
λ·u est-il nul ? False


### 4.5 Sous-espaces vectoriels : critère et exemples

Un sous-ensemble $F \subset E$ est un sous-espace vectoriel si et seulement si : (1) $0_E \in F$, (2) $F$ stable par addition, (3) $F$ stable par multiplication scalaire — condition résumée par la stabilité par combinaison linéaire $\lambda u + \mu v \in F$.

#### Contre-exemple 1 : $F_1 = \{(x,y) \mid x+y=2\}$ (droite ne passant pas par l'origine)

In [18]:
# F1 = { (x, y) ∈ R² | x + y = 2 }
# C'est une droite... mais qui ne passe PAS par l'origine.

def dans_F1(vec):
    x, y = vec
    return np.isclose(x + y, 2)

origine = np.array([0.0, 0.0])
print("F1 contient-il 0_E ?", dans_F1(origine))   # False -> déjà mort

# Pire : F1 n'est même pas stable par addition
a = np.array([1.0, 1.0])   # 1+1 = 2  ✓
b = np.array([0.0, 2.0])   # 0+2 = 2  ✓
print("a ∈ F1 ?", dans_F1(a), " | b ∈ F1 ?", dans_F1(b))
print("a+b ∈ F1 ?", dans_F1(a + b))   # (1,3) -> 1+3=4 ≠ 2 -> False

F1 contient-il 0_E ? False
a ∈ F1 ? True  | b ∈ F1 ? True
a+b ∈ F1 ? False


#### Contre-exemple 2 : $F_2 = \{(x,y) \mid x=0 \text{ ou } y=0\}$ (réunion des deux axes)

Contient bien $0_E$, mais n'est pas stable par addition.

In [19]:
# F2 = { (x, y) ∈ R² | x = 0 OU y = 0 }  (les deux axes)
# Contient bien 0_E, mais...

def dans_F2(vec):
    x, y = vec
    return np.isclose(x, 0) or np.isclose(y, 0)

u2 = np.array([1.0, 0.0])   # sur l'axe des x
v2 = np.array([0.0, 1.0])   # sur l'axe des y
print("u2 ∈ F2 ?", dans_F2(u2), " | v2 ∈ F2 ?", dans_F2(v2))
print("u2+v2 =", u2 + v2, " ∈ F2 ?", dans_F2(u2 + v2))   # (1,1) -> False

u2 ∈ F2 ? True  | v2 ∈ F2 ? True
u2+v2 = [1. 1.]  ∈ F2 ? False


#### Exemple validé : $F = \{(x,y) \mid x+y=0\}$ (droite passant par l'origine)

Les trois critères sont vérifiés un par un.

In [20]:
# F = { (x, y) ∈ R² | x + y = 0 }  (une droite passant par l'origine)

def dans_F(vec):
    x, y = vec
    return np.isclose(x + y, 0)

zero2 = np.array([0.0, 0.0])

# --- Condition 1 : 0_E ∈ F ? ---
print("1. 0_E ∈ F ?", dans_F(zero2))    # 0+0=0 -> True

# --- Condition 2 : stable par addition ? ---
# On fabrique deux éléments DE F au hasard.
# Astuce : un élément de F s'écrit (t, -t) pour t quelconque.
t1, t2 = 5.0, -3.0
a = np.array([t1, -t1])    # (5, -5)   ✓ dans F
b = np.array([t2, -t2])    # (-3, 3)   ✓ dans F
print("   a =", a, "∈ F ?", dans_F(a))
print("   b =", b, "∈ F ?", dans_F(b))
print("2. a+b =", a + b, "∈ F ?", dans_F(a + b))   # (2,-2) -> True

# --- Condition 3 : stable par multiplication scalaire ? ---
lam = -4.0
print("3. λ·a =", lam * a, "∈ F ?", dans_F(lam * a))   # (-20,20) -> True

1. 0_E ∈ F ? True
   a = [ 5. -5.] ∈ F ? True
   b = [-3.  3.] ∈ F ? True
2. a+b = [ 2. -2.] ∈ F ? True
3. λ·a = [-20.  20.] ∈ F ? True


#### Vérification globale : critère unique (combinaison linéaire) sur 1000 tirages aléatoires

In [21]:
# Théorème 3 : F est un SEV  <=>  λu + µv ∈ F  pour tous u,v ∈ F et λ,µ ∈ K.
# On teste cette condition unique (qui résume les 3) sur plein de cas au hasard.

def element_de_F():
    # génère un élément (t, -t) donc garanti dans F
    t = float(rng.integers(-9, 10))
    return np.array([t, -t])

tout_ok = True
for _ in range(1000):
    u_, v_ = element_de_F(), element_de_F()
    lam_, mu_ = float(rng.integers(-9, 10)), float(rng.integers(-9, 10))
    combinaison = lam_ * u_ + mu_ * v_
    if not dans_F(combinaison):
        tout_ok = False
        break

print("λu + µv reste dans F sur 1000 essais ?", tout_ok)   # True

λu + µv reste dans F sur 1000 essais ? True


### 4.6 Somme et somme directe de sous-espaces vectoriels

$F+G = \{u+v \mid u \in F,\, v \in G\}$. La somme est **directe** (notée $F \oplus G$) si de plus $F \cap G = \{0_E\}$ : tout élément de $F+G$ s'écrit alors de façon **unique**.

#### Exemple 15 : $F+G$ dans $\mathbb{R}^3$ — $F$ = axe des $x$, $G$ = axe des $y$

In [22]:
# F + G = { u + v | u ∈ F, v ∈ G }
# Exemple 15 du PDF, dans R³ :
#   F = { (x,0,0) }  (axe des x)
#   G = { (0,y,0) }  (axe des y)
# Un élément de F s'écrit (s,0,0), un élément de G s'écrit (0,t,0).

def elem_F():
    s = float(rng.integers(-9, 10))
    return np.array([s, 0.0, 0.0])

def elem_G():
    t = float(rng.integers(-9, 10))
    return np.array([0.0, t, 0.0])

# On génère des éléments de F+G et on regarde leur forme
print("Quelques éléments de F + G :")
for _ in range(5):
    somme = elem_F() + elem_G()
    print("  ", somme)

# Observation : tous de la forme (x, y, 0) -> F+G = { (x,y,z) | z = 0 }

Quelques éléments de F + G :
   [-6.  4.  0.]
   [-7. -9.  0.]
   [ 1. -4.  0.]
   [-1. -7.  0.]
   [-6. -1.  0.]


#### Exemple 16 : une somme non directe — $F \cap G \neq \{0_E\}$

Deux plans de $\mathbb{R}^3$ dont l'intersection est une droite : la décomposition d'un vecteur en $F+G$ n'est plus unique.

In [23]:
# Exemple 16 du PDF :
#   F = { (x,y,z) | x = 0 }  (plan yz)
#   G = { (x,y,z) | y = 0 }  (plan xz)
# On a bien F + G = R³, MAIS la somme n'est PAS directe.

# Preuve : l'intersection n'est pas réduite à {0}.
# F ∩ G : x=0 ET y=0  ->  { (0,0,z) } = tout l'axe z, pas seulement 0 !

# Conséquence : décomposition NON unique. Le PDF donne (1,2,3) :
w = np.array([1.0, 2.0, 3.0])

# Décomposition n°1 : (0,2,3) + (1,0,0)
d1_F = np.array([0.0, 2.0, 3.0]); d1_G = np.array([1.0, 0.0, 0.0])
# Décomposition n°2 : (0,2,0) + (1,0,3)
d2_F = np.array([0.0, 2.0, 0.0]); d2_G = np.array([1.0, 0.0, 3.0])

print("Décomp 1 :", d1_F, "+", d1_G, "=", d1_F + d1_G)
print("Décomp 2 :", d2_F, "+", d2_G, "=", d2_F + d2_G)
print("Deux décompositions différentes du MÊME w -> somme NON directe")
print("(car F ∩ G = axe z ≠ {0})")

Décomp 1 : [0. 2. 3.] + [1. 0. 0.] = [1. 2. 3.]
Décomp 2 : [0. 2. 0.] + [1. 0. 3.] = [1. 2. 3.]
Deux décompositions différentes du MÊME w -> somme NON directe
(car F ∩ G = axe z ≠ {0})


#### Exemple classique de somme directe : fonctions paires $\oplus$ fonctions impaires

Toute fonction $f : \mathbb{R} \to \mathbb{R}$ se décompose de façon unique en $f = f_p + f_i$ avec $f_p$ paire et $f_i$ impaire — car $P \cap I = \{0\}$ (seule la fonction nulle est à la fois paire et impaire).

In [24]:
def est_paire(f,essais = 200):
    xs = rng.uniform(-10,10,essais)
    return np.allclose([f(-x) for x in xs], [f(x) for x in xs])

def est_impaire(f, essais = 200):
    xs = rng.uniform(-10,10,essais)
    return np.allclose([f(-x) for x in xs], [-f(x) for x in xs])

#jeux de tests

print("cos paire ?   ", est_paire(np.cos))
print("sin impaire ? ", est_impaire(np.sin))
print("x³ impaire ?  ", est_impaire(lambda x: x**3))
print("x² paire ?    ", est_paire(lambda x: x**2))

cos paire ?    True
sin impaire ?  True
x³ impaire ?   True
x² paire ?     True


In [25]:
def paire_et_impaire(f):
    return est_paire(f) and est_impaire(f)

print("fonction nulle -> P ∩ I ?", paire_et_impaire(lambda x: 0*x))   # True
print("cos -> P ∩ I ?          ", paire_et_impaire(np.cos))          # False

fonction nulle -> P ∩ I ? True
cos -> P ∩ I ?           False


---

## 5. Retour aux suites : compléments

### 5.1 Rang à partir duquel $|u_n - \ell| < \varepsilon$ (définition $\varepsilon$-$N$)

In [26]:
def rang_n(u,ell,eps,fenetre = 50,nmax = 100000):
    """ renvoie le rang n à partir duquel |u_n - ell| < eps """

    for n in range(1,nmax):
        if all(abs(u(k) - ell) < eps for k in range(n, n + fenetre)):
            return n
    return None

# jeux de tests

u = lambda n : (2*n + 1)/(n + 2)

for eps in [0.1, 0.01, 0.001]:
    N = rang_n(u, 2, eps)
    print(f"Pour ε = {eps}, |u_n - 2| < ε pour n ≥ {N} (u_{N} = {u(N)})")

Pour ε = 0.1, |u_n - 2| < ε pour n ≥ 29 (u_29 = 1.903225806451613)
Pour ε = 0.01, |u_n - 2| < ε pour n ≥ 299 (u_299 = 1.9900332225913622)
Pour ε = 0.001, |u_n - 2| < ε pour n ≥ 2998 (u_2998 = 1.999)


### 5.2 Théorème des gendarmes

In [27]:
def encadrement_ok(u,v,w,debut,fin):
    """verifie le theoreme des gendarmes pour n debut a fin teste"""

    return all(u(n) <= v(n) <= w(n) for n in range(debut, fin + 1))

# jeux de tests
u = lambda n: 2 - 1/(1 + n + n**2)
v = lambda n: 2 + (-1)**n / (1 + n + n**2)
w = lambda n: 2 + 1/(1 + n + n**2)

print("Encadrement ok pour n=1..100 ?", encadrement_ok(u,v,w,0,1000))

for n in [1, 10, 100, 1000]:
    print(f"n={n:<5} u={u(n):.5f}  v={v(n):.5f}  w={w(n):.5f}")



Encadrement ok pour n=1..100 ? True
n=1     u=1.66667  v=1.66667  w=2.33333
n=10    u=1.99099  v=2.00901  w=2.00901
n=100   u=1.99990  v=2.00010  w=2.00010
n=1000  u=2.00000  v=2.00000  w=2.00000


### 5.3 Suite géométrique $u_n = a^n$

In [28]:
def geometrique(a,N):
    """ renvoie les N+1 premiers termes de la suite géométrique u_n = a^n """

    return [a**n for n in range(N + 1)]

# jeux de tests

for a in [1,2,0.5,-1.5]:
    termes = geometrique(a, 6)
    apercu = [round(t,3) for t in termes]
    print(f"a={a:<5}  u_n = {apercu}")

a=1      u_n = [1, 1, 1, 1, 1, 1, 1]
a=2      u_n = [1, 2, 4, 8, 16, 32, 64]
a=0.5    u_n = [1.0, 0.5, 0.25, 0.125, 0.062, 0.031, 0.016]
a=-1.5   u_n = [1.0, -1.5, 2.25, -3.375, 5.062, -7.594, 11.391]


---

## 6. Arithmétique — vérifications numériques

Compagnon du chapitre *Arithmétique* : divisibilité, division euclidienne, congruences, PGCD/Bézout, inverse modulaire, exponentiation rapide.

### 6.1 Exponentiation modulaire

Comparaison entre l'explosion de $3^{50}$ en clair et l'exponentiation modulaire $3^{50} \bmod 7$ (`pow(a, b, m)`), le mécanisme qui rend RSA calculable en pratique.

In [29]:
# geometrique classique : explose

print(3**50)

# geometrie modulaire : reste borné
print(pow(3,50,7)) # 4

717897987691852588770249
2


### 6.2 Divisibilité

In [30]:
def divise(a,b):
    """renvoie True si a divise b, False sinon"""
    return b % a == 0
# jeux de tests
print(divise(3,12))   # True
print(divise(5,12))   # False
print(divise(7,0))   # True

True
False
True


In [31]:
def diviseurs(n):
    """Liste tous les diviseurs positifs de n (n > 0)"""
    return [d for d in range(1,n+1) if n % d == 0]

# jeux de tests

print(diviseurs(12))  # [1, 2, 3, 4, 6, 12]
print(diviseurs(1))   # [1]
print(diviseurs(7))   # [1, 7]
print(diviseurs(13)) # [1, 2, 4, 5, 10, 20, 25, 50, 100]

[1, 2, 3, 4, 6, 12]
[1]
[1, 7]
[1, 13]


### 6.3 Combinaison linéaire et divisibilité

Si $a \mid b$ et $a \mid c$, alors $a$ divise toute combinaison $ub + vc$ — l'ingrédient clé du lemme de Bézout.

In [32]:
a,b,c = 3,12,9
u,v = 5,-2

combinaison = u*b + v*c
print(combinaison)
print(divise(a,combinaison))


42
True


### 6.4 Congruences

$a \equiv b \pmod n \iff n \mid (a-b)$.

In [33]:
n , a , b = 7,23, 2
print(a % n == b % n )
print((a - b) % n == 0)


True
True


### 6.5 Division euclidienne

$a = bq + r$ avec $0 \leqslant r < b$ — attention à l'opérateur `%` de Python qui suit déjà cette convention même pour $a < 0$.

In [34]:
a,b = 17, 5
q = a//b 
r = a % b
print(q,r)
print(a == b*q + r)

3 2
True


In [35]:
a , b = -17, 5
q = a // b
r = a % b
print(q,r)
print(a == b*q + r)

-4 3
True


In [36]:
def division_euclidienne(a,b):
    """renvoie le couple (q,r) de la division euclidienne de a par b"""
    q = a // b
    r = a % b
    return q,r

# jeux de tests
print(division_euclidienne(17,5))   # (3,2)
print(division_euclidienne(-17,5))  # (-4,3)
print(division_euclidienne(100,7))  # (14,2)

(3, 2)
(-4, 3)
(14, 2)


### 6.6 Application : chiffrement de César (décalage modulo 26)

In [37]:
lettre = 24
decalage = 3
chiffre = (lettre + decalage) % 26
print(chiffre)

1


### 6.7 PGCD — algorithme d'Euclide

In [38]:
def pgcd(a,b):
    """renvoie le plus grand commun diviseur de a et b"""
    while b != 0:
        a, b = b, a % b
    return a 
# jeux de tests
print(pgcd(12,18))  # 6
print(pgcd(48,18)) # 6
print(pgcd(17, 5))

6
6
1


In [39]:
def pgcd_rec(a,b):
    if b == 0:
        return a
    return pgcd_rec(b, a % b)

# jeux de tests
print(pgcd_rec(12,18))  # 6 
print(pgcd_rec(48,18))  # 6

6
6


In [40]:
import math
def coprimes(a,b):
    return math.gcd(a,b) == 1

print(coprimes(12,18))  # False
print(coprimes(7,40))   # True

False
True


### 6.8 Algorithme d'Euclide étendu et théorème de Bézout

$d = \mathrm{pgcd}(a,b) = au + bv$.

In [41]:
def euclide_etendu(a,b):
    """renvoie le couple (d,x,y) tel que d = pgcd(a,b) et d = ax + by"""
    if b == 0:
        return a, 1, 0
    g,u1,v1 = euclide_etendu(b, a % b)
    u = v1
    v = u1 - (a // b) * v1
    return g,u,v
# jeux de tests
g,u,v = euclide_etendu(48,18)
print(g,u,v)
print(48*u + 18*v)

6 -1 3
6


### 6.9 Inverse modulaire

$a$ est inversible modulo $n$ ssi $\mathrm{pgcd}(a,n) = 1$ ; l'inverse se lit dans l'identité de Bézout $au+nv=1$.

In [42]:
def inverse_modulaire(a,n):
    """renvoie l'inverse de a modulo n si pgcd(a,n) = 1, None sinon"""
    g,u,v = euclide_etendu(a,n)
    if g != 1:
        return None
    return u % n

#jeux de tests
print(inverse_modulaire(3,7))   # 5
print(inverse_modulaire(2,6))   # None  
print(inverse_modulaire(7,40))


5
None
23


### 6.10 Compléments sur les congruences

Compatibilité de la congruence avec les opérations : si $a \equiv b \pmod n$ et $c \equiv d \pmod n$, alors $ac \equiv bd \pmod n$.

In [43]:
# les bases modulo

n = 12
print(17 % n == 5 % n)

True


In [44]:
n = 7

a,b = 23,2
c,d = 18,4

print((a*c) % n == (b*d) % n)  # True  -> 23×18 ≡ 2×4 (mod 7)
# On peut réduire avant OU après : même résultat
print((a*c) % n)               # 5
print((b*d) % n)

True
1
1


### 6.11 Exponentiation rapide (par carrés successifs)

In [45]:
def exp_modulaire(base, exp, mod):
    """Calcule base^exp mod mod par exponentiation rapide."""
    resultat = 1
    base = base % mod
    while exp > 0:
        if exp % 2 == 1:          # bit de poids faible = 1
            resultat = (resultat * base) % mod
        exp = exp // 2            # on décale
        base = (base * base) % mod # on élève au carré
    return resultat

print(exp_modulaire(7, 100, 13))   # 9
print(pow(7, 100, 13))             # 9  -> même résultat

9
9


### 6.12 Application : chiffrement RSA

In [46]:
# parametres RSA

p, q = 61,53
n = p * q
phi = (p - 1) * (q - 1)
e = 17

d = pow(e , -1, phi)
print("d = ",d)

message = 65
chiffre = pow(message, e, n)
dechiffre = pow(chiffre, d, n)

print("chiffré   :", chiffre)      # 2790
print("déchiffré :", dechiffre)    # 65  -> on retrouve le message !



d =  2753
chiffré   : 2790
déchiffré : 65


---

## 7. Retour aux suites : séries et suites factorielles

### 7.1 Somme d'une série géométrique — vérification numérique de la formule

In [47]:
def serie_directe(a,N):
    """somme en additionnant terme a termes"""
    return sum(a ** n for n in range(N + 1))

def serie_formule(a,n):
    """meme somme mais via la formule de la somme d'une suite géométrique"""

    return (1 - a **(N + 1)) / (1 - a)

a = 0.5

for N in [5, 10, 50]:
    directe = serie_directe(a, N)
    formule = serie_formule(a, N)
    print(f"N={N:<4} directe={directe:.6f}  formule={formule:.6f}")

print(f"limite théorique 1/(1-a) = {1/(1-a)}")



N=5    directe=1.968750  formule=1.968750
N=10   directe=1.999023  formule=1.999023
N=50   directe=2.000000  formule=2.000000
limite théorique 1/(1-a) = 2.0


### 7.2 Suite $a^n/n!$ — vérification numérique de l'exercice 1.3 (décroissance à partir d'un certain rang)

In [48]:
from math import factorial

def a_n_sur_factorielle(a, N):
    """renvoie le terme général a_n = n! / (n+1)!"""
    return [a**n / factorial(n) for n in range(N + 1)]

a = 100
termes = a_n_sur_factorielle(a, 250)

# jeux de tests
for n in[10,50,100,150,250]:
    print(f"n={n:<5} a^n/n! = {termes[n]:.3e}")


n=10    a^n/n! = 2.756e+13
n=50    a^n/n! = 3.288e+35
n=100   a^n/n! = 1.072e+42
n=150   a^n/n! = 1.750e+37
n=250   a^n/n! = 3.093e+07


---

## 8. Retour à l'arithmétique : petit théorème de Fermat et indicatrice d'Euler

### 8.1 Vérification du petit théorème de Fermat

In [49]:
def verifie_fermat(a,p):
    """verifie le petit théorème de Fermat : a^(p-1) ≡ 1 (mod p)"""
    return pow(a, p - 1, p) == 1
# jeux de tests
print(verifie_fermat(3, 7))     # True   -> 3^6 ≡ 1 (mod 7)
print(verifie_fermat(2, 13))    # True   -> 2^12 ≡ 1 (mod 13)


True
True


### 8.2 Indicatrice d'Euler $\varphi(n)$

In [50]:
from math import gcd

def phi(n):
    """renvoie le nombre d'entiers positifs ≤ n et premiers avec n"""
    return sum(1 for k in range(1, n + 1) if gcd(k, n) == 1)

# jeux de tests
print(phi(1))   # 1
print(phi(2))   # 1
print(phi(3))   # 2
print(phi(4))   # 2
print(phi(5))   # 4     

1
1
2
2
4


---

## 9. Retour au chiffrement de César : cryptanalyse par force brute

On essaie les 26 décalages possibles pour retrouver le message en clair — la faiblesse structurelle du chiffre de César (espace de clés minuscule).

In [51]:
message = "WKH VHFUHW LV KLGGHQ LQ WKH JDUGHQ"

def dechiffre_cesar(texte, cle):
    """Déchiffre 'texte' avec un décalage 'cle'."""
    resultat = ""
    for c in texte:
        if c.isalpha():
            pos = ord(c) - ord('A')          # 'A'->0 ... 'Z'->25
            nouvelle_pos = (pos - cle) % 26   # décalage inverse mod 26
            resultat += chr(nouvelle_pos + ord('A'))
        else:
            resultat += c                     # espaces inchangés
    return resultat

# On teste les 26 décalages
for cle in range(26):
    print(f"clé {cle:2d} : {dechiffre_cesar(message, cle)}")

clé  0 : WKH VHFUHW LV KLGGHQ LQ WKH JDUGHQ
clé  1 : VJG UGETGV KU JKFFGP KP VJG ICTFGP
clé  2 : UIF TFDSFU JT IJEEFO JO UIF HBSEFO
clé  3 : THE SECRET IS HIDDEN IN THE GARDEN
clé  4 : SGD RDBQDS HR GHCCDM HM SGD FZQCDM
clé  5 : RFC QCAPCR GQ FGBBCL GL RFC EYPBCL
clé  6 : QEB PBZOBQ FP EFAABK FK QEB DXOABK
clé  7 : PDA OAYNAP EO DEZZAJ EJ PDA CWNZAJ
clé  8 : OCZ NZXMZO DN CDYYZI DI OCZ BVMYZI
clé  9 : NBY MYWLYN CM BCXXYH CH NBY AULXYH
clé 10 : MAX LXVKXM BL ABWWXG BG MAX ZTKWXG
clé 11 : LZW KWUJWL AK ZAVVWF AF LZW YSJVWF
clé 12 : KYV JVTIVK ZJ YZUUVE ZE KYV XRIUVE
clé 13 : JXU IUSHUJ YI XYTTUD YD JXU WQHTUD
clé 14 : IWT HTRGTI XH WXSSTC XC IWT VPGSTC
clé 15 : HVS GSQFSH WG VWRRSB WB HVS UOFRSB
clé 16 : GUR FRPERG VF UVQQRA VA GUR TNEQRA
clé 17 : FTQ EQODQF UE TUPPQZ UZ FTQ SMDPQZ
clé 18 : ESP DPNCPE TD STOOPY TY ESP RLCOPY
clé 19 : DRO COMBOD SC RSNNOX SX DRO QKBNOX
clé 20 : CQN BNLANC RB QRMMNW RW CQN PJAMNW
clé 21 : BPM AMKZMB QA PQLLMV QV BPM OIZLMV
clé 22 : AOL ZLJYLA PZ OPKKLU PU

---

## 10. Retour à Bézout : variante récursive de l'algorithme d'Euclide étendu

In [52]:
def euclide_etendu_rec(a,b):
    if b == 0:
        return a, 1, 0
    g, u1, v1 = euclide_etendu_rec(b, a % b)
    return (g,v1, u1 - (a // b) * v1)
print(euclide_etendu_rec(240,46))  # (6, -1, 3) car 48*(-1) + 18*3 = 6

(2, -9, 47)


---

## 11. Matrices

### 11.1 Produit matriciel

In [54]:
import numpy as np

A1 = np.array([[2, 1], [3, 2]])
B1 = np.array([[1, -1], [1, 2]])

print(A1 @ B1)

A2 = np.array([[1, 2,0], [3, 1,4]])

B2 = np.array([[-1,-1, 0], [1,4, -1], [2,1, 2]])

print(A2 @ B2)

[[3 0]
 [5 1]]
[[ 1  7 -2]
 [ 6  5  7]]


### 11.2 Matrices de rotation — lien avec les nombres complexes et les groupes

On vérifie numériquement puis symboliquement que $A(\theta)A(\theta') = A(\theta+\theta')$ et $A(\theta)^n = A(n\theta)$ : les matrices de rotation forment un groupe isomorphe à $(\mathbb{U}, \times)$ (le cercle unité de $\mathbb{C}$) via $\theta \mapsto e^{i\theta}$.

In [56]:
import numpy as np
import sympy as sp

# --- Vérification numérique ---
def A(theta):
    return np.array([[np.cos(theta), -np.sin(theta)],
                     [np.sin(theta),  np.cos(theta)]])

theta, theta_p = 0.7, 1.2

# A(θ)·A(θ') == A(θ+θ') ?
print(np.allclose(A(theta) @ A(theta_p), A(theta + theta_p)))  # True

# A(θ)^n == A(nθ) ?
n = 5
print(np.allclose(np.linalg.matrix_power(A(theta), n), A(n*theta)))  # True

# --- Preuve symbolique avec sympy ---
th, thp = sp.symbols('theta theta_prime', real=True)

def As(t):
    return sp.Matrix([[sp.cos(t), -sp.sin(t)],
                      [sp.sin(t),  sp.cos(t)]])

produit = sp.simplify(sp.trigsimp(As(th) * As(thp)))
print(produit)          # Matrix([[cos(θ+θ'), -sin(θ+θ')], [sin(θ+θ'), cos(θ+θ')]])
print(As(th + thp))     # identique

True
True
Matrix([[cos(theta + theta_prime), -sin(theta + theta_prime)], [sin(theta + theta_prime), cos(theta + theta_prime)]])
Matrix([[cos(theta + theta_prime), -sin(theta + theta_prime)], [sin(theta + theta_prime), cos(theta + theta_prime)]])
